FROM eclipse-temurin:17-jdk-alpine
EXPOSE 8080
ADD target/spring-boot-rest-service-hello-world-0.0.1-SNAPSHOT.jar spring-boot-rest-service-hello-world-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/spring-boot-rest-service-hello-world-0.0.1-SNAPSHOT.jar"]
