apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: custom-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels: {}  
  policyTypes:
  - Ingress
  - Egress  
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0  
    ports:
    - protocol: TCP
      port: -1
