apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend-service
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /greeting
            pathType: Prefix
            backend:
              service:
                name: spring-boot-rest-hello-world
                port:
                  number: 8080